/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\black_gold_sneakers_fleur_de_lis_style.glb -t -T 
Files: .\public\models\black_gold_sneakers_fleur_de_lis_style.glb [9.49MB] > C:\Users\liubo\WebstormProjects\pu-master-commerce\black_gold_sneakers_fleur_de_lis_style-transformed.glb [1.2MB] (87%)
*/

import * as THREE from 'three'
import React, { JSX } from "react";
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Fleur-de-Lis_black_shoe_None_0']: THREE.Mesh
  }
  materials: {
    None: THREE.MeshStandardMaterial
  }
  animations: ""
}

export function BlackGoldShoesModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/black_gold_sneakers_fleur_de_lis_style-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Fleur-de-Lis_black_shoe_None_0'].geometry} material={materials.None} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/black_gold_sneakers_fleur_de_lis_style-transformed.glb')
