/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\scan_kids_shoes_freepolyorg.glb -t -T 
Files: .\public\models\scan_kids_shoes_freepolyorg.glb [38.69MB] > C:\Users\liubo\WebstormProjects\pu-master-commerce\scan_kids_shoes_freepolyorg-transformed.glb [744.77KB] (98%)
*/

import * as THREE from 'three'
import React, { JSX } from "react";
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Kids_Shoes__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
  animations: ""
}

export function KidsShoesModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scan_kids_shoes_freepolyorg-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Kids_Shoes__0.geometry} material={materials['Scene_-_Root']} position={[-0.004, -0.002, -0.219]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scan_kids_shoes_freepolyorg-transformed.glb')
