/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\new_balance_500.glb -t -T 
Files: .\public\models\new_balance_500.glb [28.15MB] > C:\Users\liubo\WebstormProjects\pu-master-commerce\new_balance_500-transformed.glb [1.33MB] (95%)
*/

import * as THREE from 'three'
import React, { JSX } from "react";
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Model_material0_0: THREE.Mesh
  }
  materials: {
    material0: THREE.MeshBasicMaterial
  }
  animations: ""
}

export function NewBalanceShoesModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/new_balance_500-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/new_balance_500-transformed.glb')
