/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\shoes_outdoor.glb -t -T 
Files: .\public\models\shoes_outdoor.glb [36.28MB] > C:\Users\liubo\WebstormProjects\pu-master-commerce\shoes_outdoor-transformed.glb [1.55MB] (96%)
*/

import * as THREE from 'three'
import React, { JSX } from "react";
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['GERRIT_Material_#25_0']: THREE.Mesh
  }
  materials: {
    Material_25: THREE.MeshStandardMaterial
  }
  animations: ""
}

export function OutdoorShoesModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/shoes_outdoor-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['GERRIT_Material_#25_0'].geometry} material={materials.Material_25} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/shoes_outdoor-transformed.glb')
