/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\sports_shoes.glb -t -T 
Files: .\public\models\sports_shoes.glb [2.99MB] > C:\Users\liubo\WebstormProjects\pu-master-commerce\sports_shoes-transformed.glb [351.99KB] (88%)
*/

import * as THREE from 'three'
import React, { JSX } from "react";
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
  animations: ""
}

export function SportsShoesModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/sports_shoes-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} position={[-0.001, -0.237, 0.01]} scale={0.622} />
    </group>
  )
}

useGLTF.preload('/sports_shoes-transformed.glb')
